import type { ParsedPalette } from "@/lib/color-builder/types";

export const MANUAL_TEMPLATE = `## Color Palette 1
- Palette Name: ...
- Color 1: ...
- Color 2: ...
- Color 3: ...
- Color n: ...

## Color Palette 2
- Palette Name: ...
- Color 1: ...
- Color 2: ...
- Color 3: ...
- Color n: ...

## Color Palette 3
- Palette Name: ...
- Color 1: ...
- Color 2: ...
- Color 3: ...
- Color n: ...

## Color Palette n
- Palette Name: ...
- Color 1: ...
- Color 2: ...
- Color 3: ...
- Color n: ...`;

export const MANUAL_TEMPLATE_BLOCK = ["```md", MANUAL_TEMPLATE, "```"].join("\n");

export function createCanonicalMarkdown(palettes: ParsedPalette[]): string {
  const body = palettes
    .map((palette, paletteIndex) => {
      const colorLines = palette.colors.map(
        (color, colorIndex) => `- Color ${colorIndex + 1}: ${color.source}`,
      );

      return [
        `## Color Palette ${paletteIndex + 1}`,
        `- Palette Name: ${palette.name}`,
        ...colorLines,
      ].join("\n");
    })
    .join("\n\n");

  return ["```md", body, "```"].join("\n");
}
